version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" GitHubOrg=\"enokawa\" RepositoryName=\"sam-cicd-sample\" OIDCProviderArn=\"\""
image_repositories = []