name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        python-version: [ '3.9' ]

    permissions:
      contents: 'read'
      id-token: 'write' 

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: pip install
        run: pip install -r tests/requirements.txt

      - name: Unit test
        run: python -m pytest tests/unit -v
      
      - name: Integration test
        run: 

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/dev-OIDCRole
          role-session-name: SAMDeploySession

      - name: sam build
        run: sam build

      - name: sam deploy
        run: sam deploy --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --no-confirm-changeset --no-fail-on-empty-changeset